Repository kcl-lang/kcl-lang.io, pull requests merged in 2023-07, with the labels that each got.

#97 docs: add command reference for kpm.
  docs/reference/package-management/_category_.json
  docs/reference/package-management/command-reference/1.init.md
  docs/reference/package-management/command-reference/10.help.md
  docs/reference/package-management/command-reference/2.add.md
  docs/reference/package-management/command-reference/3.pkg.md
  docs/reference/package-management/command-reference/4.metadata.md
  docs/reference/package-management/command-reference/5.run.md
  docs/reference/package-management/command-reference/6.login.md
  docs/reference/package-management/command-reference/7.logout.md
  docs/reference/package-management/command-reference/8.push.md
  docs/reference/package-management/command-reference/9.pull.md
  docs/reference/package-management/command-reference/_category_.json
  docs/reference/package-management/command-reference/index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/_category_.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/1.init.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/10.help.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/2.add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/3.pkg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/4.metadata.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/5.run.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/6.login.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/7.logout.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/8.push.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/9.pull.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/_category_.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/package-management/command-reference/index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/_category_.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/1.init.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/10.help.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/2.add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/3.pkg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/4.metadata.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/5.run.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/6.login.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/7.logout.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/8.push.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/9.pull.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/_category_.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/package-management/command-reference/index.md
  versioned_docs/version-0.5.0/reference/package-management/_category_.json
  versioned_docs/version-0.5.0/reference/package-management/command-reference/1.init.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/10.help.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/2.add.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/3.pkg.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/4.metadata.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/5.run.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/6.login.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/7.logout.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/8.push.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/9.pull.md
  versioned_docs/version-0.5.0/reference/package-management/command-reference/_category_.json
  versioned_docs/version-0.5.0/reference/package-management/command-reference/index.md
Labels: documentation

#101 fix: update 'go install kpm'.
  docs/user_docs/guides/package-management/2-installation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/2-installation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/package-management/2-installation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/package-management/2-installation.md
  versioned_docs/version-0.4.6/user_docs/guides/package-management/2-installation.md
  versioned_docs/version-0.5.0/user_docs/guides/package-management/2-installation.md
Labels: enhancement

#104 feat: add user guides for 'kpm push'.
  docs/user_docs/guides/package-management/4-share_your_pkg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-share_your_pkg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/package-management/4-share_your_pkg.md
  versioned_docs/version-0.5.0/user_docs/guides/package-management/4-share_your_pkg.md
Labels: documentation

#96 doc: update vscode docs
  docs/tools/Ide/vs-code.md
  versioned_docs/version-0.5.0/tools/Ide/vs-code.md
Labels: documentation

#111 feat: add kcl v0.5.0 release blogs
  blog/2022-09-15-declarative-config-overview/index.md
  blog/2023-07-14-kcl-0.5.0-release/index.md
  i18n/zh-CN/docusaurus-plugin-content-blog/2022-09-15-declarative-config-overview/index.md
  i18n/zh-CN/docusaurus-plugin-content-blog/2023-07-14-kcl-0.5.0-release/index.md
  static/img/blog/2023-07-14-kcl-0.5.0-release/app-ci.png
  static/img/blog/2023-07-14-kcl-0.5.0-release/app.png
  static/img/blog/2023-07-14-kcl-0.5.0-release/argocd-app.png
  static/img/blog/2023-07-14-kcl-0.5.0-release/argocd-sync.png
  static/img/blog/2023-07-14-kcl-0.5.0-release/auto-update.png
Labels: release
